image: ruby:2.6

pages:
  stage: build
  script:
    - cp UALib/html/UALib.md index.md
    - cp UALib/html/*.md .
    - cp UALib/md/*.md .
    - bundle install --path vendor
    - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
