image: ruby:2.1

pages:
  script:
  - gem install jekyll
  - jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - master



# pages:
#   stage: deploy
#   script:
#   - mkdir .public
#   - cp -r * .public
#   - mv .public public
#   artifacts:
#     paths:
#     - public
#   only:
#   - masterimage: alpine

# pages:
#   script:
#   - apk --no-cache add py3-pip python3-dev 
#   - pip3 install sphinx
#   - pip3 install sphinxcontrib-bibtex sphinxcontrib-proof sphinxcontrib-tikz
#   - pip3 install https://bitbucket.org/gebner/pygments-main/get/default.tar.gz#egg=Pygments
#   - apk --no-cache add make
#   - make html
#   - mv _build/html/ public/
#   artifacts:
#     paths:
#     - public
#   only:
#   - master
  
# image: alpine

# pages:
#   script:
#   - apk --no-cache add py2-pip python-dev
#   - pip install https://bitbucket.org/gebner/pygments-main/get/default.tar.gz#egg=Pygments
#   - pip install sphinx
#   - pip install sphinxcontrib-bibtex sphinxcontrib-proof sphinxcontrib-tikz
#   - apk --no-cache add make
#   - make html
#   - mv _build/html/ public/
#   artifacts:
#     paths:
#     - public
#   only:
#   - master
