image: alpine

pages:
  script:
  - apk --no-cache add py3-pip python3-dev 
  - pip3 install sphinx
  - pip3 install sphinxcontrib-bibtex sphinxcontrib-proof sphinxcontrib-tikz
  - pip3 install https://bitbucket.org/gebner/pygments-main/get/default.tar.gz#egg=Pygments
  - apk --no-cache add make
  - make html
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
# - pip install 'wheel>=0.29' # needed for old ubuntu versions, https://github.com/pallets/markupsafe/issues/59
  